### ISSUE TITLE
Hi Marcin

### ISSUE THREAD

**Issue by rpelaez** [hvqzao/jgantt#1]
Hello Marcin, good job with the plugin, very very nice!

I want to make some modifications to the code (for example obtain date from date-time fields and others to track with links dependencies) and to publish for free in the Atlassian Marketplace in this web: https://marketplace.atlassian.com/vendors/1212608/www-mraddon-com

I would like your permission to do so.
Many thanks for your attention

**Comment by rpelaez** [comment]
Amazing!
![Captura de pantalla 2019-07-19 a las 21 08 13](https://user-images.githubusercontent.com/1374732/61559163-596b4100-aa69-11e9-829e-a08e9b63f226.png)

**Comment by hvqzao** [comment]
Hello, sure, please go ahead :)

**Comment by rpelaez** [comment]
Hello Marcin, now is alive!
https://marketplace.atlassian.com/apps/1221236/kanban-gantt-for-jira-jgantt?hosting=server&tab=overview

If you see something wrong, please let me know and I will fix it! Thanks for all!
